# Generated by Django 2.1.15 on 2021-07-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='box.Deposito', verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='box.Situacao', verbose_name='Situação'),
        ),
    ]