# Generated by Django 2.1.15 on 2021-07-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Padrão', max_length=50, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativo')),
                ('conf_autorizacao', models.ManyToManyField(blank=True, related_name='conf_autorizacao', to='box.Situacao', verbose_name='Exigir autorização para as situações')),
                ('conf_situacao', models.ManyToManyField(blank=True, related_name='conf_situcao', to='box.Situacao', verbose_name='Oculta a situação para o colaborador')),
                ('list_completo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo_listar_depositoss_completo', to='auth.Group', verbose_name='Lista geral dos depósitos')),
                ('list_restrito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo_listar_depositoss_restrito', to='auth.Group', verbose_name='Lista restrita por usuário de depósitos')),
            ],
            options={
                'verbose_name': 'Configuração',
            },
        ),
    ]