# Generated by Django 2.1.15 on 2021-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, default='pbkdf2_sha256$120000$yLM2DajPvfG8$CiftUZRNbXvl3NiqS5GjFZHafJ0PlwYsaBJSZq0LOSI=', max_length=250, null=True),
        ),
    ]
