# Generated by Django 2.1.15 on 2021-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210721_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, default='pbkdf2_sha256$120000$XfdNIFZQeZo2$rHRGsj3M6uxmY6egTve5pkElEN8KPfPLLn4T8Za+1OM=', max_length=250, null=True),
        ),
    ]
